# Generated by Django 5.0 on 2024-01-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['created'], 'verbose_name': 'Enlace', 'verbose_name_plural': 'Enlaces'},
        ),
    ]
